// Generated by scripts/build_optical_shaders.ps1 from AMD FidelityFX 1.1.4 (MIT).
#include "Pass0.h"
static const char* kP0R0Names[] = {"cbOF"};
static const uint32_t kP0R0Slot[] = {0};
static const uint32_t kP0R0Count[] = {1};
static const uint32_t kP0R0Space[] = {0};
static const char* kP0R1Names[] = {"r_input_color"};
static const uint32_t kP0R1Slot[] = {0};
static const uint32_t kP0R1Count[] = {1};
static const uint32_t kP0R1Space[] = {0};
static const char* kP0R2Names[] = {"rw_optical_flow_input"};
static const uint32_t kP0R2Slot[] = {0};
static const uint32_t kP0R2Count[] = {1};
static const uint32_t kP0R2Space[] = {0};
#include "Pass1.h"
static const char* kP1R2Names[] = {"rw_optical_flow_input","rw_optical_flow_input_level_1","rw_optical_flow_input_level_2","rw_optical_flow_input_level_3","rw_optical_flow_input_level_4","rw_optical_flow_input_level_5","rw_optical_flow_input_level_6"};
static const uint32_t kP1R2Slot[] = {0,1,2,3,4,5,6};
static const uint32_t kP1R2Count[] = {1,1,1,1,1,1,1};
static const uint32_t kP1R2Space[] = {0,0,0,0,0,0,0};
#include "Pass2.h"
static const char* kP2R0Names[] = {"cbOF"};
static const uint32_t kP2R0Slot[] = {0};
static const uint32_t kP2R0Count[] = {1};
static const uint32_t kP2R0Space[] = {0};
static const char* kP2R1Names[] = {"r_optical_flow_input"};
static const uint32_t kP2R1Slot[] = {0};
static const uint32_t kP2R1Count[] = {1};
static const uint32_t kP2R1Space[] = {0};
static const char* kP2R2Names[] = {"rw_optical_flow_scd_histogram"};
static const uint32_t kP2R2Slot[] = {0};
static const uint32_t kP2R2Count[] = {1};
static const uint32_t kP2R2Space[] = {0};
#include "Pass3.h"
static const char* kP3R2Names[] = {"rw_optical_flow_scd_histogram","rw_optical_flow_scd_previous_histogram","rw_optical_flow_scd_temp","rw_optical_flow_scd_output"};
static const uint32_t kP3R2Slot[] = {0,1,2,3};
static const uint32_t kP3R2Count[] = {1,1,1,1};
static const uint32_t kP3R2Space[] = {0,0,0,0};
#include "Pass4.h"
static const char* kP4R0Names[] = {"cbOF"};
static const uint32_t kP4R0Slot[] = {0};
static const uint32_t kP4R0Count[] = {1};
static const uint32_t kP4R0Space[] = {0};
static const char* kP4R1Names[] = {"r_optical_flow_input","r_optical_flow_previous_input"};
static const uint32_t kP4R1Slot[] = {0,1};
static const uint32_t kP4R1Count[] = {1,1};
static const uint32_t kP4R1Space[] = {0,0};
static const char* kP4R2Names[] = {"rw_optical_flow","rw_optical_flow_scd_output"};
static const uint32_t kP4R2Slot[] = {0,1};
static const uint32_t kP4R2Count[] = {1,1};
static const uint32_t kP4R2Space[] = {0,0};
#include "Pass5.h"
static const char* kP5R1Names[] = {"r_optical_flow_previous"};
static const uint32_t kP5R1Slot[] = {0};
static const uint32_t kP5R1Count[] = {1};
static const uint32_t kP5R1Space[] = {0};
static const char* kP5R2Names[] = {"rw_optical_flow"};
static const uint32_t kP5R2Slot[] = {0};
static const uint32_t kP5R2Count[] = {1};
static const uint32_t kP5R2Space[] = {0};
#include "Pass6.h"
static const char* kP6R0Names[] = {"cbOF"};
static const uint32_t kP6R0Slot[] = {0};
static const uint32_t kP6R0Count[] = {1};
static const uint32_t kP6R0Space[] = {0};
static const char* kP6R1Names[] = {"r_optical_flow_input","r_optical_flow_previous_input","r_optical_flow"};
static const uint32_t kP6R1Slot[] = {0,1,2};
static const uint32_t kP6R1Count[] = {1,1,1};
static const uint32_t kP6R1Space[] = {0,0,0};
static const char* kP6R2Names[] = {"rw_optical_flow_next_level","rw_optical_flow_scd_output"};
static const uint32_t kP6R2Slot[] = {0,1};
static const uint32_t kP6R2Count[] = {1,1};
static const uint32_t kP6R2Space[] = {0,0};
static const FfxShaderBlob kOpticalBlobs[] = {{ kOpticalPass0, sizeof(kOpticalPass0), 1, 1, 1, 0, 0, 0, 0, kP0R0Names, kP0R0Slot, kP0R0Count, kP0R0Space, kP0R1Names, kP0R1Slot, kP0R1Count, kP0R1Space, kP0R2Names, kP0R2Slot, kP0R2Count, kP0R2Space, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
{ kOpticalPass1, sizeof(kOpticalPass1), 0, 0, 7, 0, 0, 0, 0, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, kP1R2Names, kP1R2Slot, kP1R2Count, kP1R2Space, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
{ kOpticalPass2, sizeof(kOpticalPass2), 1, 1, 1, 0, 0, 0, 0, kP2R0Names, kP2R0Slot, kP2R0Count, kP2R0Space, kP2R1Names, kP2R1Slot, kP2R1Count, kP2R1Space, kP2R2Names, kP2R2Slot, kP2R2Count, kP2R2Space, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
{ kOpticalPass3, sizeof(kOpticalPass3), 0, 0, 4, 0, 0, 0, 0, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, kP3R2Names, kP3R2Slot, kP3R2Count, kP3R2Space, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
{ kOpticalPass4, sizeof(kOpticalPass4), 1, 2, 2, 0, 0, 0, 0, kP4R0Names, kP4R0Slot, kP4R0Count, kP4R0Space, kP4R1Names, kP4R1Slot, kP4R1Count, kP4R1Space, kP4R2Names, kP4R2Slot, kP4R2Count, kP4R2Space, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
{ kOpticalPass5, sizeof(kOpticalPass5), 0, 1, 1, 0, 0, 0, 0, nullptr, nullptr, nullptr, nullptr, kP5R1Names, kP5R1Slot, kP5R1Count, kP5R1Space, kP5R2Names, kP5R2Slot, kP5R2Count, kP5R2Space, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr },
{ kOpticalPass6, sizeof(kOpticalPass6), 1, 3, 2, 0, 0, 0, 0, kP6R0Names, kP6R0Slot, kP6R0Count, kP6R0Space, kP6R1Names, kP6R1Slot, kP6R1Count, kP6R1Space, kP6R2Names, kP6R2Slot, kP6R2Count, kP6R2Space, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr }};
